Feature/ngr lookup
DEFRA/waste-exemptions-acceptance-tests pull request #3
Opened 2017-01-03 11:50 UTC by timstone

2017-01-03 16:30 UTC, Cruikshanks requested changes
I've completed PR #5 to get the admin nav bar section in. That should hopefully clean up some of the stuff around working with the menu.

I'd suggest getting that in first  i.e. complete #5, merge it in, rebase this branch on `master`, and then update it to use the section.

We can then go from there.

2017-01-04 11:00 UTC, timstone commented
@Cruikshanks rebased with master

2017-01-05 11:20 UTC, Cruikshanks requested changes
Just some tidying up to do in the `.feature` file.

Also looks like we merged in the admin section stuff rather than rebasing on `master`. No biggy, but I can show you how to **rebase** instead, and what the difference is next time.

2017-01-05 11:20 UTC, Cruikshanks commented on features/backoffice_site_address.feature
> +Feature: Back office user registers a customers new waste exemption activity
Could we make the feature description more relevant to the test i.e. try and put something in here as to why we need to capture the EA admin area

2017-01-05 11:20 UTC, Cruikshanks commented on features/backoffice_site_address.feature
> +
Remove the extra lines and ensure we have a carriage return at the end of document.

2017-01-05 11:20 UTC, Cruikshanks commented on features/backoffice_site_address.feature
> +     When I complete a registration using a <postcode> for site address
Just sort out the grammar. Perhaps...
```gherkin
When I complete a registration using postcode <postcode> for the site address
```

2017-01-05 11:20 UTC, Cruikshanks commented on features/backoffice_site_address.feature
> +     Then I will be able to check what the National Grid Reference <ngr> is for the site
Just sort out the grammar. Perhaps...

```gherkin
Then I will see the site's National Grid Reference has been automatically found to be <ngr>
```

2017-01-05 11:20 UTC, Cruikshanks commented on features/backoffice_site_address.feature
> +     And I will be told what <area> that site is located in
Just sort out the grammar. Perhaps...

```gherkin
And I will see the EA admin area is set to <area>
```

2017-01-05 13:50 UTC, timstone commented
@Cruikshanks I've updated features as discussed.

2017-01-05 13:58 UTC, Cruikshanks approved these changes

2017-01-05 15:10 UTC, Cruikshanks commented
When you do the merge in Github @timstone can you use the drop down and select **Squash & merge**. This will ensure we clean up the commits on this branch before merging them into `master`. Come give me a shout if you need a hand.

2017-01-05 15:19 UTC, merged